s28/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('web.urls')),


]

web/models.py
from django.db import models

# Create your models here.


class UserInfo(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=32, db_index=True)
    email = models.EmailField(verbose_name='邮箱', max_length=32)
    mobile_phone = models.CharField(verbose_name='手机号', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=32)


class Student_Information(models.Model):
    # 姓名
    name = models.CharField(max_length=200)

    # 学号
    address = models.CharField(max_length=200)

    # 图片
    img = models.ImageField(upload_to='img')


class Distinguish(models.Model):
    # 学生状态
    state = models.CharField(max_length=200)

    # 识别人数
    Number = models.BigIntegerField()

    # 具体信息
    specific = models.TextField(blank=True, null=True)


class Eachclass(models.Model):
    # 第几节课
    Thatclass = models.CharField(max_length=200)
    # 认真听讲人数
    Earnestpeopl = models.BigIntegerField()
    # 平均专注度值
    Focusvalue = models.BigIntegerField()

web/templates/administration.html
{% extends 'layout/basic.html' %}
{% load static %}


{% block title %} 智慧管理 {% endblock %}
{{ num }}

{% block css %}
    <style>
    *{
        margin: 0 auto;
    }
        .navbar{
                margin: 0;
                padding: 0;
            }
        .wai{
            width: 1536px;
            height: 700px;
            background-color: #b3b1b1;
        }
        .left{
            width: 400px;
            height: 690px;
            background-color: #e8e8e8;
            float:left;
            margin: 5px;
        }
        .center{
            width: 965px;
            height: 480px;
            background-color: #d5d4d4;
            float:left;
            margin: 5px 5px 5px 0;
        }
        .right{
            width: 151px;
            height: 480px;
            background-color: #d3d4d3;
            float:right;
            margin: 5px 5px 5px 0;
        }
        .xia{
            width: 1121px;
            height: 205px;
            background-color: #c7c7c7;
            float:right;
            margin: 0px 5px 5px 0;
        }
    #zhu{
        min-width:1120px;
        height:162px;
    }
    .panel-body{
        margin: 0;
        padding: 0;
    }
    #bin{
        height: 320px;
    }
    #zhuzhuang{
        height: 328px;
    }
    .LU{
			margin: 0px 0px;
			width: auto;/*宽度*/
			height: 50px;/*长度*/
			padding: 0px;
		}
    .LI{
			margin: 4px 4px 2px 4px;
			width: 141px;
			height: auto;
			list-style-type: none;/* 去掉li的点 */
			float: left;
		}
    .A{

			margin: 0px 0px;
			display: block;/*将a变成块*/
			width: auto;
			height: auto;
			font-family: 微软雅黑;
			line-height: 50px;/*设置字体高度*/
			background-color: #fdfdfc;
			color: #393939;
			text-align: center;/*字体居中*/
			text-decoration: none;/*去掉下划线*/
			font-size: 15px;

    }
    a:hover{
			background-color: #f5eded;
		}
    </style>
{% endblock %}


{% block content %}
    <div class="wai">
        <div class="left panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-caret-square-o-right" aria-hidden="true"></i>
                    数据分析
                </div>
                <div class="panel-body">
                    <div id="container">
                        <div class="#">
                            <div id="bin"></div>
                            <div id="zhuzhuang"></div>
                        </div>
                    </div>
                </div>
        </div>
        <div class="center panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-caret-square-o-right" aria-hidden="true"></i>
                    地图
                </div>
                <div class="panel-body">
                    <div id="container">
                        <div class="#">
                            <img src="/static/img/school/校园地图{{ num }}.gif" width="963px" height="437px">
                        </div>
                    </div>
                </div>
        </div>
        <div class="right panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-caret-square-o-right" aria-hidden="true"></i>
                    学生
                </div>
                <div class="panel-body">
                    <div id="container">
                        <div class="#">
                            <ul class="LU">
                                <li class="LI panel panel-default"><a class="A" href="1">1990101黄意山</a></li>
                                <li class="LI panel panel-default"><a class="A" href="2">1990102颜睿</a></li>
                                <li class="LI panel panel-default"><a class="A" href="0">1990103田菊艳</a></li>
                                <li class="LI panel panel-default"><a class="A" href="0">1990101杨红艳</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
        </div>
        <div class="xia panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-caret-square-o-right" aria-hidden="true"></i>
                    进出统计
                </div>
                <div class="panel-body">
                    <div id="container">
                        <div id="zhu" ></div>
                    </div>
                </div>
        </div>



    </div>

{% endblock %}


{% block js %}
        <script src="https://code.highcharts.com.cn/highcharts/highcharts.js"></script>
        <script src="https://code.highcharts.com.cn/highcharts/modules/exporting.js"></script>
        <script src="https://code.highcharts.com.cn/highcharts/modules/oldie.js"></script>
        <script src="https://img.hcharts.cn/highcharts-plugins/highcharts-zh_CN.js"></script>
        <script src="https://code.highcharts.com.cn/highcharts/highcharts-3d.js"></script>
        <script src="https://code.highcharts.com.cn/highcharts/themes/sand-signika.js"></script>
        <script src="https://code.highcharts.com.cn/highcharts/modules/cylinder.js"></script>
<script>
{#    条形图#}
       var chart = Highcharts.chart('zhu', {
    chart: {
        type: 'bar'
    },
    title: {
        text: null
    },
    xAxis: {
        categories: ['教学楼', '食堂', '图书馆']
    },
    yAxis: {
        min: 0,
        title: {
            text: null
        }
    },
           credits:{
                    enabled: false //关闭版权信息
                },
    legend: {
        /* 图例显示顺序反转
         * 这是因为堆叠的顺序默认是反转的，可以设置
         * yAxis.reversedStacks = false 来达到类似的效果
         */
        reversed: true
    },
    plotOptions: {
        series: {
            stacking: 'normal'
        }
    },
    series: [{
        name: '上午',
        data: [5, 3, 4]
    }, {
        name: '下午',
        data: [2, 2, 3]
    }, {
        name: '晚上',
        data: [3, 4, 4]
    }]
});
    {#   饼图#}
    var chart = Highcharts.chart('bin', {
		chart: {
				type: 'pie',
				options3d: {
						enabled: true,
						alpha: 45,
						beta: 0
				}
		},
		title: {
				text: '学生在不同地点停留占比率'
		},
        credits:{
                    enabled: false //关闭版权信息
                },
		tooltip: {
				pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
		},
		plotOptions: {
				pie: {
						allowPointSelect: true,
						cursor: 'pointer',
						depth: 35,
						dataLabels: {
								enabled: true,
								format: '{point.name}'
						}
				}
		},
		series: [{
				type: 'pie',
				name: '停留时间占比',
				data: [
						['寝室',   45.0],
						['教室',       26.8],
						{
								name: '图书馆',
								y: 12.8,
								sliced: true,
								selected: true
						},
						['食堂',    8.5],
						['实训楼',     6.2],
						['办公楼',   0.7]
				]
		}]
});
    {#柱状图#}
    Highcharts.chart('zhuzhuang', {
	chart: {
		type: 'cylinder',
		options3d: {
			enabled: true,
			alpha: 20,
			beta: 0,
			depth: 0,
			viewDistance: 25
		}
	},
    credits:{
                    enabled: false //关闭版权信息
                },
	title: {
		text: '学生在不同地点停留时长'
	},
	plotOptions: {
		series: {
			depth: 25,
			colorByPoint: true
		}
	},
    yAxis: {
        title: {
            text: '停留时长（h）'
        },
        endOnTick: false,
    },
    xAxis:{
                    categories:['寝室','教室','图书馆','食堂','实训楼','办公楼']
                },
	series: [{
		data: [8, 5.5, 4, 1.2, 1.5, 0.5],
		name: '停留时间（h）',
		showInLegend: false
	}]
});
    </script>
{% endblock %}

web/templates/concentration.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %} 专注度 {% endblock %}
{{ datas }}
{{ focus }}

{% block css %}

    <link rel="stylesheet" href="/static/plugin/bootstrap/css/bootstrap.min.css">

    <style>
        .navbar{
            margin: 0;
            padding: 0;
        }
        .cootent{
                height: 912px;
                width: 1520px;
				background-color: #b3b1b1;
			}
        .left{
            display: inline-block;
            float: left;
            width: 1080px;
            height: 655px;

            margin: 5px;
        }
        #im{
            width: 1048px;
            height: 580px;
        }
        .right{
            display: inline-block;
            float: right;
            width: 425px;
            height: 902px;
            margin: 5px 5px 5px 0;
        }
        .bottom{
            display: inline-block;
            float: left;
            width: 1080px;
            height: 242px;
            background-color: #d5d5d5;
            margin: 0 5px 5px 5px;
        }
        td:empty {
            background-color:#dddddd;
        }
    </style>
{% endblock %}

{% block content %}
    <div  class="cootent">


        <div class="left panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-caret-square-o-right" aria-hidden="true"></i>
                实时展现
            </div>
            <div class="panel-body">
                <div id="container">
{#                    <img id="im" src="/static/img/concentration/1.jpg"/>#}
                    <img id="im" src="http://127.0.0.1:8000/getVideo" >
{#                    <script type="text/javascript">#}
{#                        setInterval("changeImg()",10);#}
{#                        i=1#}
{#                        function changeImg(){#}
{#                            var SImg = document.getElementById('im');#}
{#                            SImg.src="/static/img/concentration/" + i%10 + ".jpg";#}
{#                            i;#}
{#                        }#}
{#		            </script>#}
                </div>
            </div>
        </div>

        <div class="right panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bar-chart" aria-hidden="true"></i>
                数据统计
            </div>
            <div class="panel-body">
                <div id="container" style="width: 100%;min-height: 800px">
                    <div id="chart" style="width: auto;height:274px;"></div>
                    <div id="barchart" style="width: auto;height: 274px;"></div>
                    <div id="priority" style="width: auto;height: 274px;"></div>
                </div>
            </div>
        </div>



        <div class="bottom panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-calendar-o" aria-hidden="true"></i>
                识别信息
            </div>
            <div class="panel-body" style="padding: 0;">
                <div id="container" >
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>学生状态</th>
                                <th>识别人数</th>
                                <th>具体信息</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for data in datas %}
                            <tr>
                                <td>{{ data.id }}</td>
                                <td>{{ data.state }}</td>
                                <td>{{ data.Number }}</td>
                                <td>{{ data.specific }}</td>
                            </tr>
                        {% endfor %}

                    </tbody>

                    </table>
                </div>
            </div>
        </div>

    </div>
{% endblock %}


{% block js %}
    {#饼状图需要的文件#}


    <script src="/static/plugin/daterangepicker/moment.min.js"></script>
    <script src="/static/plugin/daterangepicker/daterangepicker.js"></script>
    <script src="/static/plugin/highcharts/highcharts.js"></script>

    <script src="https://code.highcharts.com.cn/highcharts/highcharts.js"></script>
    <script src="https://code.highcharts.com.cn/highcharts/modules/exporting.js"></script>
    <script src="https://img.hcharts.cn/highcharts-plugins/highcharts-zh_CN.js"></script>

    <script src="https://code.highcharts.com.cn/highcharts/themes/dark-unica.js"></script>
    <script>
        //统计图表
        var INIT_CHART = "{% url 'issues_chart'  %}";
        var PRIORITY= "{% url 'issues_priority' %}";
        var BARCHART= "{% url 'issues_barchart' %}";
        $(function () {
            initChart();
            priority();
            barchart();
        });
        //折现图
        //---------------------------------------------------------------------------
        function initChart(){
            //chart
            var config = {
                title: {
                        text: '高二（3）班学生专注度值统计总汇'
                },
                credits:{
                    enabled: false //关闭版权信息
                },
                yAxis: {
                        title: {
                                text: '专注值'
                        },
                        endOnTick: false,
                        maxPadding: 0.2
                },
                xAxis:{
                    categories:['第一节','第二节','第三节','第四节','第五节','第六节','第七节','第八节']
                },
                legend: {
                        enabled:false
                        {#layout: 'vertical',#}
                        {#align: 'right',#}
                        {#verticalAlign: 'middle'#}
                },
                series: [{
				name: '专注度平局值',
				data: [

                ]
		        },],
            };
            {#var chart = Highcharts.chart('chart',config)#}
            $.ajax({
                url: INIT_CHART,
                type: "GET",
                dataType: "JSON",
                success: function (res) {
                    config.series[0].data = res.data;
                    Highcharts.chart('chart', config);
                }
            });
        }
        //条形图
        //---------------------------------------------------------------------------
        function barchart() {
            var config = {chart: {
        type: 'column'
    },
    title: {
        text: '班级课堂人数统计'
    },
    subtitle: {
        text: null
    },
    xAxis: {
        type: 'category',

        labels: {
            rotation: -45  // 设置轴标签旋转角度
        }
    },
    yAxis: {
        min: 0,
        title: {
            text: '人'
        }
    },
    legend: {
        enabled: false
    },
    tooltip: {
        pointFormat: '人数: <b>{point.y:.1f} 人</b>'
    },
    series: [{
        name: '总人口',
        data: [],
        dataLabels: {
            enabled: true,
            rotation: -90,
            color: '#FFFFFF',
            align: 'right',
            format: '{point.y:0f}', // :.1f 为保留 1 位小数
            y: 10
        }
    }]};
            $.ajax({
                url: BARCHART,
                type: "GET",
                dataType: "JSON",
                success: function (res) {
                    config.series[0].data = res.data;
                    Highcharts.chart('barchart', config);
                }
            });
        }
        //饼状图
        //---------------------------------------------------------------------------

function priority(){
        var config = {
                chart: {
                    type: 'pie'
                },
                title: {
                    text: "班级睡觉人数占比"
                },
                credits: {
                    enabled: false // 关闭版权信息
                },
                tooltip: {
                    pointFormat: '{series.name}: <b>{point.y} %</b>'
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: false
                        },
                        showInLegend: true
                    }
                },
                series: [{
                    name: '比例',
                    colorByPoint: true,
                    data: []
                }]
            };
            $.ajax({
                url:PRIORITY,
                type:"GET",
                dataType:"JSON",
                success:function(res){
                    config.series[0].data=res.data;
                    Highcharts.chart('priority',config);
                }
            })
}
        //---------------------------------------------------------------------------
    </script>
{% endblock %}

web/templates/index.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %} 首页 {% endblock %}

{% block css %}
    <style>
    .navbar{
            margin: 0;
            padding: 0;
        }
        img {
            width: 100%;
        }


    </style>
{% endblock %}

{% block content %}
    <div CLASS="ex">

        <img src="/static/img/index/index.png">
    </div>

{% endblock %}

web/templates/login.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %} 用户登录 {% endblock %}


{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
        .error-msg {
            color: red;
            position: absolute;
            font-size: 13px;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="account">
        <div class="title">用户登录</div>
        <form method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row">
                            <div class="col-xs-7">
                                {{ field }}
                                <span class="error-msg">{{ field.errors.0 }}</span>
                            </div>
                            <div class="col-xs-5">
                                <img src="{% url 'image_code' %}" id="imageCode" title="点击更换图片">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg">{{ field.errors.0 }}</span>
                    </div>
                {% endif %}
            {% endfor %}

            <div>
                <div style="float: right;">
                    <a href="{% url 'login_sms' %}">短信验证码登录?</a>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-3">
                    <input type="submit" class="btn btn-primary" value="登  录"/>
                </div>
            </div>
        </form>
    </div>
{% endblock %}


{% block js %}
    <script>
        $(function () {
            $('#imageCode').click(function () {
                var oldSrc = $(this).attr('src');
                $(this).attr('src', oldSrc + "?");
            })
        })
    </script>
{% endblock %}

web/templates/login_sms.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %} 用户短信登录 {% endblock %}


{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
        .error-msg {
            color: red;
            position: absolute;
            font-size: 13px;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="account">
        <div class="title">用户短信登录</div>
        <form id="smsForm" method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row">
                            <div class="col-xs-7">
                                {{ field }}
                                <span class="error-msg"></span>
                            </div>
                            <div class="col-xs-5">
                                <input id="btnSms" type="button" class="btn btn-default" value="点击获取验证码">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg"></span>
                    </div>
                {% endif %}
            {% endfor %}
            <div>
                <div style="float: right;">
                    <a href="{% url 'login' %}">用户名密码登录?</a>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3">
                    <input id="btnSubmit" type="button" class="btn btn-primary" value="登  录"/>
                </div>
            </div>
        </form>
    </div>
{% endblock %}


{% block js %}
    <script>
        // 页面框架加载完成之后自动执行函数
        $(function () {
            bindClickBtnSms();
            bindClickSubmit();
        });

        /*
        点击登录
        */
        function bindClickSubmit() {
            $('#btnSubmit').click(function () {
                $('.error-msg').empty();
                // 收集表单中的数据（找到每一个字段）$('#regForm').serialize()
                // 数据ajax发送到后台
                $.ajax({
                    url: "{% url 'login_sms' %}",
                    type: "POST",
                    data: $('#smsForm').serialize(), // 所有字段数据 + csrf token
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            location.href = res.data;
                        } else {
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }

        /*
       点击获取验证码的按钮绑定事件
        */
        function bindClickBtnSms() {
            $('#btnSms').click(function () {

                $('.error-msg').empty();

                // 获取用户输入的手机号
                // 找到输入框的ID，根据ID获取值，如何找到手机号的那个ID？
                var mobilePhone = $('#id_mobile_phone').val();

                // 发送ajax请求，把手机号发送过去
                $.ajax({
                    url: "{% url 'send_sms' %}", // 等价于 /send/sms/
                    type: "GET",
                    data: {mobile_phone: mobilePhone, tpl: "login"},
                    dataType: "JSON", // 将服务端返回的数据反序列化为字典
                    success: function (res) {
                        // ajax请求发送成功之后，自动执行的函数； res就是后端返回的值
                        if (res.status) {
                            sendSmsRemind();
                        } else {
                            // 错误信息
                            // console.log(res); // {status:False, error:{ mobile_phone: ["错误信息"，],code: ["错误信息"，] }  }
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })

            })
        }

        /*
        倒计时
         */
        function sendSmsRemind() {
            var $smsBtn = $('#btnSms');
            $smsBtn.prop('disabled', true); // 禁用
            var time = 60;
            var remind = setInterval(function () {
                $smsBtn.val(time + '秒重新发送');
                time = time - 1;
                if (time < 1) {
                    clearInterval(remind);
                    $smsBtn.val('点击获取验证码').prop('disabled', false);
                }
            }, 1000)

        }
    </script>
{% endblock %}

web/templates/register.html
{% extends 'layout/basic.html' %}

{% block title %}用户注册{% endblock %}


{% block css %}
    <link rel="stylesheet" href="\static\css\account.css">
    <style>
        .error-msg {
            color: red;
            position: absolute;
            font-size: 13px;
        }
    </style>

{% endblock %}


{% block content %}
    <div class="account">
        <div class="title">用户注册</div>
        <form id="regForm" method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row">
                            <div class="col-xs-7">
                                {{ field }}
                                <span class="error-msg"></span>
                            </div>
                            <div class="col-xs-5">
                                <input id="btnSms" type="button" class="btn btn-default" value="点击获取验证码">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg"></span>
                    </div>
                {% endif %}
            {% endfor %}

            <div class="row">
                <div class="col-xs-3">
                    <input id="btnSubmit" type="button" class="btn btn-primary" value="注  册"/>
                </div>
            </div>
        </form>
    </div>
{% endblock %}


{% block js %}
    <script>
        // 页面框架加载完成之后自动执行函数
        $(function () {
            bindClickBtnSms();
            bindClickSubmit();
        });
        /*
        点击提交（注册）
        */
        function bindClickSubmit() {
            $('#btnSubmit').click(function () {
                $('.error-msg').empty();
                // 收集表单中的数据（找到每一个字段）$('#regForm').serialize()
                // 数据ajax发送到后台
                $.ajax({
                    url: "{% url 'register' %}",
                    type: "POST",
                    data: $('#regForm').serialize(), // 所有字段数据 + csrf token
                    dataType: "JSON",
                    success: function (res) {
                        if(res.status){
                            location.href = res.data;
                        }else{
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }
        /*
        点击获取验证码的按钮绑定事件
         */
        function bindClickBtnSms() {
            $('#btnSms').click(function () {

                $('.error-msg').empty();

                // 获取用户输入的手机号
                // 找到输入框的ID，根据ID获取值，如何找到手机号的那个ID？
                var mobilePhone = $('#id_mobile_phone').val();

                // 发送ajax请求，把手机号发送过去
                $.ajax({
                    url: "{% url 'send_sms' %}", // 等价于 /send/sms/
                    type: "GET",
                    data: {mobile_phone: mobilePhone, tpl: "register"},
                    dataType: "JSON", // 将服务端返回的数据反序列化为字典
                    success: function (res) {
                        // ajax请求发送成功之后，自动执行的函数； res就是后端返回的值
                        if (res.status) {
                            sendSmsRemind();
                        } else {
                            // 错误信息
                             //console.log(res); // {status:False, error:{ mobile_phone: ["错误信息"，],code: ["错误信息"，] }  }
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })

            })
        }

        /*
        倒计时
         */
        function sendSmsRemind() {
            var $smsBtn = $('#btnSms');
            $smsBtn.prop('disabled', true); // 禁用
            var time = 60;
            var remind = setInterval(function () {
                $smsBtn.val(time + '秒重新发送');
                time = time - 1;
                if (time < 1) {
                    clearInterval(remind);
                    $smsBtn.val('点击获取验证码').prop('disabled', false);
                }
            }, 1000)

        }

    </script>

{% endblock %}